Merged PR 1388: [2210] Merge fileserver into rygg
# Implementation Summary
-------------------------------
To handle the datasets feature efficiently, we need fileserver and rygg running in the same process. With tricks for docker-compose volumes that we've added recently, the fileserver functionality doesn't need to run in the same container as the kernel.

# [Optional] How to review
-------------------------------
Make sure there's no remaining stuff from fileserver.
Make sure it runs for you.

# What did you do to make the codebase a better place? How did you make the improvements durable
-------------------------------
*Here you should describe what improvements you made to codebase while working on the ticket.*
*Note that the improvements should be proportional in size to the main objective of the ticket*

# Please also:
- [X] Include any new files in included_files.txt
- [ ] Update the story on the board
- [ ] Announce changes that will affect everyone in #dev in slack

[2210] Merge fileserver into rygg

Related work items: #2210

diff --git a/scripts/check_included_files b/scripts/check_included_files
--- a/scripts/check_included_files
+++ b/scripts/check_included_files
@@ -37,12 +37,32 @@ reject_patterns=$(cat included_files_exceptions.txt| awk "/^regex:/" | sed "s/re
 for l in $reject_patterns; do
   extra_files=$(echo "$extra_files" | awk "$l") || true
 done
-report_error "${extra_files}" "Extra files:"
+
 
 missing_files=$(join -v 2 "${present}" "${expected}" | join -v 2 "${exceptions}" -)
-report_error "${missing_files}" "Missing files:"
 
-rm "${expected}" "${present}" "${exceptions}"
+# missing files that are a full prefix (a root dir) of extra files are actually there
+# add / to each missing file
+without_slash=$(echo "${missing_files}" | sed 's/^\(.*[^\/]\)$/\1/g')
+
+pruned_extra_file=$(mktemp)
+pruned_missing_file=$(mktemp)
+# for each file in missing, see if we find it as a prefix n the list of extras. Yes it's O(n^2)
+for line in "${without_slash}"; do
+  if echo "${extra_files}" | grep -q "^${line}/"; then
+    echo "${extra_files}" | grep -v "^${line}/" >> "${pruned_extra_file}" || true
+  else
+    echo "${line}" >> "${pruned_missing_file}"
+  fi
+done
+
+pruned_extra="$(cat ${pruned_extra_file})"
+report_error "${pruned_extra}" "Extra files:"
+
+pruned_missing=$(cat "${pruned_missing_file}")
+report_error "${pruned_missing}" "Missing files:"
+
+rm "${expected}" "${present}" "${exceptions}" "${pruned_extra_file}" "${pruned_missing_file}"
 
 popd > /dev/null
 exit $rc
